[package]
name = "aochatproxy"
version = "4.0.1"
authors = ["Jens Reidel <adrian@travitia.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "4.0"
env_logger = { version = "0.8", default-features = false, features = ["termcolor", "atty", "humantime"] }
log = "0.4"
nadylib = { git = "https://github.com/Nadybot/nadylib", branch = "unstable", default-features = false }
serde = { version = "1.0", features = ["derive"] }
deser-hjson = "0.1"
serde_json = { version = "1.0", optional = true }
simd-json = { version = "0.4", default-features = false, features = ["serde_impl"], optional = true }
tokio = { version = "1", default-features = false, features = ["macros", "rt-multi-thread"] }

[features]
default = ["serde-json"]
serde-json = ["serde_json"]

[profile.release]
codegen-units = 1
debug = false
incremental = false
lto = true
opt-level = 3
panic = "abort"
