[package]
name = "aochatproxy"
version = "0.1.0"
authors = ["Jens Reidel <adrian@travitia.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "4.0.0-rc.6"
dotenv = "0.15"
env_logger = { version = "0.8", default-features = false, features = ["termcolor", "atty", "humantime"] }
futures-util = { version = "0.3", default-features = false, features = ["std"] }
log = "0.4"
nadylib = { git = "https://github.com/Nadybot/nadylib", branch = "unstable", default-features = false }
tokio = { version = "1.0", default-features = false, features = ["macros", "rt-multi-thread"] }

[profile.release]
lto = "thin"
