name: Build binaries

on:
  push:
    branches:
      - unstable
      - stable
    tags:
      - '*'
  pull_request:

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install cross compilers
        run: |
          apt install gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf -y

      - name: Set up Rust for x86_64
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Build for x86_64
        run: |
          cargo build --release
          cp target/release/aochatproxy aochatproxy-linux-x86_64

      - name: Set up Rust for aarch64
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: aarch64-unknown-linux-gnu
          override: true

      - name: Build for aarch64
        run: |
          cargo build --release --target=aarch64-unknown-linux-gnu
          cp target/aarch64-unknown-linux-gnu/release/aochatproxy aochatproxy-linux-aarch64

      - name: Set up Rust for armv7
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: armv7-unknown-linux-gnueabihf
          override: true

      - name: Build for armv7
        run: |
          cargo build --release --target=armv7-unknown-linux-gnueabihf
          cp target/armv7-unknown-linux-gnueabihf/release/aochatproxy aochatproxy-linux-armv7

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: aochatproxy-linux
          path: |
            aochatproxy-linux-x86_64
            aochatproxy-linux-aarch64
            aochatproxy-linux-armv7

  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Build
        run: |
          cargo build --release
          cp target/release/aochatproxy aochatproxy-macos

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: aochatproxy-macos
          path: |
            aochatproxy-macos

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Build
        run: |
          cargo build --release
          cp target/release/aochatproxy.exe aochatproxy-windows.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: aochatproxy-windows
          path: |
            aochatproxy-windows.exe
